networks:
  default:
    name: training-network

services:
  spring-microservice:
    container_name: spring-microservice
    image: spring-microservice
    ports:
      - "80:9000"

  spring-microservice2:
    container_name: spring-microservice2
    image: spring-microservice-client
    ports:
      - "81:9001"

  react-service:
    container_name: react-service
    image: react-service
    ports:
      - "5000:80"
    volumes: 
      - /c/training/nginx.conf:/etc/nginx/nginx.conf:ro


version: '3.5'
